'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Lessons
    
    '''<summary>
    '''LessonsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LessonsPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''IntroButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IntroButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''SelectButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''WhereButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WhereButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''InsertButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InsertButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DeleteButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LessonIntroPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LessonIntroPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LessonContentPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LessonContentPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LessonVideoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LessonVideoLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LessonContentsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LessonContentsLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ActivityPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActivityPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ActivityNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActivityNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ActivityTaskLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActivityTaskLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ActivityTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActivityTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ActivitySolutionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActivitySolutionLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ActivityResponseLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActivityResponseLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ActivityResultsGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActivityResultsGridView As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''ActivitySqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActivitySqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''IntroFooterPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IntroFooterPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''IntroContinueButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IntroContinueButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''FooterPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FooterPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''DownloadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DownloadButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LikeButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LikeButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LessonIdHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LessonIdHF As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''LessonDownloadURLHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LessonDownloadURLHF As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''IsLikedHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IsLikedHF As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ActivityAnswerHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActivityAnswerHF As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ActivityIsCorrectHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActivityIsCorrectHF As Global.System.Web.UI.WebControls.HiddenField
End Class
