'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm2
    
    '''<summary>
    '''ProfilePicture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProfilePicture As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''Rank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Rank As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ProgressLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProgressLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LessonActALabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LessonActALabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LessonActCLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LessonActCLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LessonActULabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LessonActULabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AchUnlockedLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AchUnlockedLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AchRemaining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AchRemaining As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ActivityRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActivityRepeater As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''UserLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CheckIdentityHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckIdentityHF As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ProfilePictureHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProfilePictureHiddenField As Global.System.Web.UI.WebControls.HiddenField
End Class
